### ISSUE TITLE
Suggestion for some more Channels

### ISSUE THREAD

**Issue by metinkale38** [itasli/IPTVTR#8]
Hey,

there are some more Channels you could add to the Dini/Religous Group:

**Lalegül TV**
http://www.lalegultv.com.tr/terms/canli-yayin
http://lalegultv.netmedya.net/hls/lalegultv.m3u8

**Semerkand TV**
http://www.semerkandtv.com.tr/canli-yayin
https://b01c02nl.mediatriple.net/videoonlylive/mtisvwurbfcyslive/broadcast_58d915bd40efc.smil/playlist.m3u8

I could not find the m3u8 Urls, but it would also be nice to have "Makkah TV" and "Madinah TV" (they are on YT as live video if it helps)

**Comment by itasli** [comment]
Thanks for suggestions

I had already add in the server a weekago, I wa just waiting to update the channel list. If you wan't you can make a pull request to add lalegul.m3u8, semerkand.m3u8 and kudus.m3u8 using the same pattern. If not the list will get updated once I had enought time.
